version: 2.1

workflows:
  version: 2
  build-project:
    jobs:
      - build:
          filters:
            branches:
              only:
                - circleci
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - circleci

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: dependencies-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install packages
          command: yarn install
      - save_cache:
          key: dependencies-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Build code
          command: yarn build
      - run:
          name: Zip the dist
          command: zip -r dist.zip dist
      - store_artifacts:
          path: dist.zip
          name: dist
  deploy:
    docker:
      - image: ubuntu:latest
    steps:
      - run:
          command: apt-get update && apt-get install rsync -y -qq && apt-get install curl -y -qq && apt-get install unzip -y -qq
      - run:
          command: which ssh-agent || (apt-get install openssh-client -y)
      - run: 
          command: eval $(ssh-agent -s)
      - run:
          command: mkdir -p ~/.ssh
      - run:
          command: echo "$(echo $SSH_PRIVATE_KEY | base64 -d)" | tr -d '\r' > ~/.ssh/circleci
      - run:
          command: chmod 700 ~/.ssh/circleci
      - run:
          command: eval "$(ssh-agent -s)"
      - run:
          command: ssh-add ~/.ssh/circleci
      - run:
          command: echo "$IP" >> ~/.ssh/known_hosts
      - run:
          command: curl -H "Circle-Token:\ $CIRCLE_TOKEN" https://circleci.com/api/v1.1/project/github/$GITHUB_USER/$PROJECT_NAME/latest/artifacts
      - run:
          command: unzip dist.zip -d dist/
      - run:
          command: rsync -aRvzhe "ssh -i ~/.ssh/circleci" --progress dist $USER@$IP:~/gerpan-blog-be -yes
      # - run:
      #     command: ssh -i ~/.ssh/circleci -o StrictHostKeyChecking=no $USER@$IP "cd ~/gerpan-blog-be && chmod 777 ./deploy.sh && ./deploy.sh"