version: 2.1

workflows:
  version: 2
  build-project:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main

jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore node_modules
          key: dependencies-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install packages
          command: yarn install
      - save_cache:
          name: Store node_modules
          key: dependencies-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Build code
          command: yarn build
      - run:
          name: Zip the dist
          command: zip -r dist.zip dist
      - store_artifacts:
          name: Store dist artifact
          path: dist.zip
  deploy:
    docker:
      - image: cimg/base:stable-20.04
    steps:
      - run:
          name: Update packages & Install rsync
          command: sudo apt-get update && sudo apt-get install rsync -y -qq
      - run:
          name: Create directory .ssh
          command: mkdir -p ~/.ssh
      - run:
          name: Write SSH_PRIVATE_KEY of VPS to new ssh file
          command: echo "$(echo $SSH_PRIVATE_KEY | base64 -d)" | tr -d '\r' > ~/.ssh/circleci
      - run:
          name: Make permission for ssh file
          command: chmod 700 ~/.ssh/circleci && ssh-add ~/.ssh/circleci
      - run:
          name: Download artifact (built dist)
          command: curl -H "Circle-Token:\ $CIRCLE_TOKEN" https://circleci.com/api/v1.1/project/github/$GITHUB_USER/$PROJECT_NAME/latest/artifacts | grep -o 'https://[^"]*' | wget --verbose --header "Circle-Token:\ $CIRCLE_TOKEN" --input-file -
      - run:
          name: Unzip the dist
          command: unzip dist.zip
      - run:
          name: Send built files to VPS
          command: rsync -aRvzhe "ssh -i ~/.ssh/circleci" --progress dist $USER@$IP:~/gerpan-blog-be -e "ssh -o StrictHostKeyChecking=no"
      - run:
          name: Run file deploy.sh in VPS
          command: ssh -i ~/.ssh/circleci -o StrictHostKeyChecking=no $USER@$IP "cd ~/gerpan-blog-be && chmod 700 ./deploy.sh && ./deploy.sh"